# Библиотека `NumPy`: часть 2

*Алла Тамбовцева*

## Домашнее задание 

### Описание домашнего задания и формат сдачи

В домашнем задании необходимо решить предложенные задачи по программированию – вписать свой код в ячейки после условий задач вместо комментария `### YOUR CODE HERE ###` в файле *homework-numpy2.ipynb* и сохранить изменения, используя опцию *Save and Checkpoint* из вкладки меню *File* или кнопку *Save and Checkpoint* на панели инструментов. Итоговый файл в формате `.ipynb` (файл Jupyter Notebook) необходимо загрузить в личный кабинет обучающей онлайн платформы Skillbox (https://go.skillbox.ru/) и отправить на проверку.

### Задание 1
Загрузить из файла `array_hw.npy` массив и сохранить его как `arr`. Массив содержит объёмы продаж мороженого (в штуках) в 5 магазинах за одну неделю в июне (7 дней, с понедельника до воскресенья). В заданиях 2-5 нужно работать с массивом `arr`.

In [4]:
### YOUR CODE HERE ###
import numpy as np
arr = np.load("array_hw.npy")
arr

array([[100,  80,  70,  60, 120],
       [ 65,  55,  20,  50,  60],
       [ 80,  90,  75,  80,  60],
       [ 45,  60,  70,  20,  40],
       [ 82,  47,  56,  89,  92],
       [115, 120, 113, 106, 107],
       [ 46,  74,  23,  34,  19]], dtype=int64)

### Задание 2
Если думать о массиве `arr` как о таблице, сейчас в таблице магазины идут по столбцам (1 магазин = 1 столбец, всего 5), а дни – по строкам (1 день = 1 строка, всего 7). Преобразовать массив `arr` таким образом, чтобы по строкам шли магазины, а по столбцам – дни (1 строка = 1 магазин). Сохранить изменения. Проверить, что форма массива изменилась.

In [5]:
### YOUR CODE HERE ###
arr_T = arr.T
arr_T

array([[100,  65,  80,  45,  82, 115,  46],
       [ 80,  55,  90,  60,  47, 120,  74],
       [ 70,  20,  75,  70,  56, 113,  23],
       [ 60,  50,  80,  20,  89, 106,  34],
       [120,  60,  60,  40,  92, 107,  19]], dtype=int64)

In [6]:
np.save("arr_T_hm11.npy",arr_T)

In [8]:
arr_T_new = np.load("arr_T_hm11.npy")
arr_T_new

array([[100,  65,  80,  45,  82, 115,  46],
       [ 80,  55,  90,  60,  47, 120,  74],
       [ 70,  20,  75,  70,  56, 113,  23],
       [ 60,  50,  80,  20,  89, 106,  34],
       [120,  60,  60,  40,  92, 107,  19]], dtype=int64)

### Задание 3

Давайте представим, что информация по продажам обновилась: оказалось, что пятый магазин в воскресенье продал не 19 порций мороженого, а 25, и второй магазин продал во вторник не 55 порций, а 65. Изменить массив `arr` в соответствии с этой информацией.

In [10]:
### YOUR CODE HERE ###
arr[0] # проверка, что это магазины в конкретный день

array([100,  80,  70,  60, 120], dtype=int64)

In [11]:
arr_chage = arr.copy()
arr_chage[6][4] = 25
arr_chage[1][1] = 65
arr_chage

array([[100,  80,  70,  60, 120],
       [ 65,  65,  20,  50,  60],
       [ 80,  90,  75,  80,  60],
       [ 45,  60,  70,  20,  40],
       [ 82,  47,  56,  89,  92],
       [115, 120, 113, 106, 107],
       [ 46,  74,  23,  34,  25]], dtype=int64)

In [12]:
arr_chage == arr # для проверки изменений

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

### Задание 4

Посчитать суммарный объём продаж мороженого по всем магазинам.

In [16]:
### YOUR CODE HERE ###
sum_sale = np.zeros(5, int)
sum_sale

array([0, 0, 0, 0, 0])

In [17]:
for day in arr_chage:
    sum_sale += day

sum_sale

array([533, 536, 427, 439, 504])

### Задание 5

Выгрузить обновлённый массив `arr` в txt-файл. Сам txt-файл загружать в систему не нужно, только написать соответствующий код в ipynb-файл.

In [20]:
### YOUR CODE HERE ###
np.savetxt("arr_chage_hm11.txt", arr_chage)

### Задание 6
Дан массив `income`, содержащий значения прибыли магазина в тысячах на начало, середину и конец года, за четыре года подряд (значения никак не сгруппированы, можно считать, что они так выгрузились из файла). 
Изменить форму массива так, чтобы значения были сгруппированы по три значения в каждом списке внутри массива (прибыль на начало, середину и конец года).

In [21]:
# массив
income = np.array([1000, 2000, 3500, 
                   2500, 1500, 3800, 
                   1200, 9000, 12000,
                   4500, 6700, 11000])

In [23]:
### YOUR CODE HERE ###
income.reshape(-1, 3)

array([[ 1000,  2000,  3500],
       [ 2500,  1500,  3800],
       [ 1200,  9000, 12000],
       [ 4500,  6700, 11000]])

### Задание 7
Создать список `turnout` (*list*, не массив), содержащий следующие значения явки на избирательные участки в процентах:

23.56, 45.78, 34.92, 57.34, 56.55, 67.23.

Создать, используя списковые включения и встроенные, не из `NumPy`, функции для округления, новый список `turnout_r`, который состоит из округлённых до первого знака после запятой значений явки из `turnout`.

In [24]:
### YOUR CODE HERE ###

turnout = [23.56, 45.78, 34.92, 57.34, 56.55, 67.23]
turnout

[23.56, 45.78, 34.92, 57.34, 56.55, 67.23]

In [26]:
turnout_r = [round(x,1) for x in turnout]
turnout_r

[23.6, 45.8, 34.9, 57.3, 56.5, 67.2]

### Задание 8
Выполнить те же операции, что и в предыдущей задаче, но с использованием массивов и функций `NumPy`. Другими словами, создать массив `turnout` и на его основе создать массив `turnout_r` с округлёнными до первого знака значениями явки.

In [27]:
### YOUR CODE HERE ###
turnout_np = np.array(turnout)
turnout_np

array([23.56, 45.78, 34.92, 57.34, 56.55, 67.23])

In [29]:
turnout_np_r = turnout_np.round(1)
turnout_np_r

array([23.6, 45.8, 34.9, 57.3, 56.6, 67.2])

### Задание 9

Зайдите на [страницу](https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D0%B4%D1%83%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9_%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81_%D1%81%D1%87%D0%B0%D1%81%D1%82%D1%8C%D1%8F) Википедии, посвящённую Международному индексу счастья, выберите из таблицы **2012 Международный индекс счастья** любые 5 стран и любые 3 показателя и создайте структурированный массив `happy`, такой, в котором есть поле «название страны» и поля для трёх выбранных показателей. Выберите подходящий тип для каждого поля (показателя) в массиве и учтите это при создание структурированного массива. Выведите полученный массив на экран.

In [33]:
### YOUR CODE HERE ###

happy = np.array([("Израиль", 55.2, 7.4, 81.6),
                 ("Норвегия", 51.4, 7.6, 81.1),
                 ("Индия", 50.9, 5, 65.4),
                 ("Великобритания", 47.9, 7, 80.2),
                 ("Япония", 47.5, 6.1, 83.4)], dtype = [('Страна', 'U15'),
                                                        ('HPI', np.dtype('float32')),
                                                        ('Удовлетворённость жизнью', np.dtype('float32')),
                                                        ('Ожидаемая продолжительность жизни', np.dtype('float32'))])

In [34]:
happy

array([('Израиль', 55.2, 7.4, 81.6), ('Норвегия', 51.4, 7.6, 81.1),
       ('Индия', 50.9, 5. , 65.4), ('Великобритания', 47.9, 7. , 80.2),
       ('Япония', 47.5, 6.1, 83.4)],
      dtype=[('Страна', '<U15'), ('HPI', '<f4'), ('Удовлетворённость жизнью', '<f4'), ('Ожидаемая продолжительность жизни', '<f4')])

In [35]:
happy[1]

('Норвегия', 51.4, 7.6, 81.1)

In [36]:
happy["Страна"]

array(['Израиль', 'Норвегия', 'Индия', 'Великобритания', 'Япония'],
      dtype='<U15')

### Задание 10
Сконвертируйте полученный в предыдущей задаче структурированный массив в обычный список и выведите на экран его второй элемент.

In [37]:
### YOUR CODE HERE ###
happy_list = happy.tolist()
happy_list

[('Израиль', 55.20000076293945, 7.400000095367432, 81.5999984741211),
 ('Норвегия', 51.400001525878906, 7.599999904632568, 81.0999984741211),
 ('Индия', 50.900001525878906, 5.0, 65.4000015258789),
 ('Великобритания', 47.900001525878906, 7.0, 80.19999694824219),
 ('Япония', 47.5, 6.099999904632568, 83.4000015258789)]

In [38]:
happy_list[1]

('Норвегия', 51.400001525878906, 7.599999904632568, 81.0999984741211)

.<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> .<br> 
# Дополнительное (необязательное) задание.
<br>

### Задание 1

Написать функцию `build_array()`, которая принимает на вход размерность квадратной матрицы (двумерного массива, в котором число строк и число столбцов совпадают) и создаёт единичную матрицу `E` (массив) соответствующей размерности. Использовать готовую функцию `np.eye()` нельзя, можно использовать циклы и условные конструкции.

**Пример:**

Ввод:

    build_array(4)

Вывод:

    array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
       
**Подсказка:** про циклы, условные конструкции, функции и двумерные массивы можно почитать в соответствующих разделах pythontutor.ru: [цикл for](http://pythontutor.ru/lessons/for_loop/), [условия](http://pythontutor.ru/lessons/ifelse/), [функции](http://pythontutor.ru/lessons/functions/) и [массивы](http://pythontutor.ru/lessons/2d_arrays/).

In [48]:
### YOUR CODE HERE ###
def build_array(dimension: int):
    E = np.zeros((dimension,dimension), float)
    for i in range(dimension):
        E[i,i] = 1
    return E

In [49]:
build_array(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Задание 2

Напишите функцию `my_reshape()`, которая принимает на вход массив и его новую размерность (пару чисел), и:

* если указанные измерения корректны, то возвращает массив новой размерности;
* если указанные измерения некорректны, то возвращает пустой массив (пример: из массива 2×5 нельзя сделать новый массив 4×3, потому что в старом массиве 10 элементов, а в новом – 12).

**Пример:**

Ввод:

    A = np.array([[2, 4, 6], 
            [4, 8, 10]])

    my_reshape(A, 6, 1)

Вывод:

    array([[2], 
       [4], 
       [6], 
       [4], 
       [8],
       [10]])

Ввод:

    A = np.array([[2, 4, 6], 
            [4, 8, 10]])

    my_reshape(A, 4, 2)

Вывод:

    array([])

**Примечание:** результаты в выводе могут визуально отличаться (выводиться без переносов по строкам, с указанием типа данных), это нормально, примеры модифицированы для читаемости.

**Подсказка:** см. материалы, предложенные в задаче 1.

In [60]:
### YOUR CODE HERE ###
def my_reshape(A, dimension_1: int, dimension_2: int):
    if A.size == (dimension_1*dimension_2):
        return A.reshape(dimension_1,dimension_2)
    else:
        return np.array([])

In [61]:
A = np.array([[2, 4, 6], [4, 8, 10]])
my_reshape(A,10,1)

array([], dtype=float64)

In [62]:
A = np.array([[2, 4, 6], [4, 8, 10]])
my_reshape(A,6,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 4],
       [ 8],
       [10]])